package com.adure.hassabi01.core.colors

import androidx.compose.runtime.Immutable
import androidx.compose.runtime.staticCompositionLocalOf
import androidx.compose.ui.graphics.Color

@Immutable
data class CustomColors(
    val commonWhiteColor: Color,
    val commonBlackColor: Color,
    val appCommonColor: Color,
    val placeHolderColor: Color,
    val SheetBg: Color,
    val BandsBg: Color,
    val BandsBorder: Color,
    val TrackColor: Color,
    val TrackBorder: Color,
    val ThumbTop: Color,
    val ThumbBot: Color,
    val KnobTop: Color,
    val KnobBot: Color,
    val KnobBorder: Color,
    val AccentRed: Color,
    val LabelGray: Color,
    val TitleColor: Color,
    val PresetActive: Color,
    val PresetInactive: Color,
    val PresetBorder: Color,
    val DividerColor: Color,
    val HandleColor: Color,
    val ZeroLineColor: Color,
    val PlayingCard: Color,
    val GlassWhite: Color,
    val PlayingBorder: Color,
    val GlassBorder: Color,
    val PlayingTitle: Color,
    val SubColor: Color,
    val DurColor: Color,
    val commonWhite:Color,
    val DividerColo: Color,
    val ZeroLineCol: Color,
    val RailBg: Color,
    val appCommonCo: Color,

    val equBandsBg : Color,
    val nobTop : Color,
    val equKnobBot : Color,
    val equKnobBorder : Color
)


val LightCustomColors = CustomColors(
    commonBlackColor = Color(0xFF000000),
    commonWhiteColor = Color(0xFFFFFFFF),
    appCommonColor = Color(0xFF5E40B3),
    placeHolderColor = Color(0xFFA3A3A3),
    SheetBg = Color(0xFFF2F0E9),
    BandsBg = Color(0xFFE8E5DD),
    BandsBorder = Color(0xFFD8D5CD),
    TrackColor = Color(0xFFC8C5BD),
    TrackBorder = Color(0xFFB5B2AA),
    ThumbTop = Color(0xFFFFFFFF),
    ThumbBot = Color(0xFFD0CEC6),
    KnobTop = Color(0xFFFFFFFF),
    KnobBot = Color(0xFFC2C0B8),
    KnobBorder = Color(0xFFB5B2AA),
    AccentRed = Color(0xFFFF4444),
    LabelGray = Color(0xFFAAAAAA),
    TitleColor = Color(0xFF333333),
    PresetActive = Color(0xFF222222),
    PresetInactive = Color(0xFFE8E5DD),
    PresetBorder = Color(0xFFCCC8C0),
    DividerColor = Color(0xFFDAD8D0),
    HandleColor = Color(0xFFCCCAC2),
    ZeroLineColor = Color(0x33FF3C3C),
    PlayingCard = Color(0xBFFFFFFF),
    GlassWhite = Color(0x73FFFFFF),
    PlayingBorder = Color(0x66A478FF),
    GlassBorder = Color(0xBFFFFFFF),
    PlayingTitle = Color(0xFF7040CC),
    SubColor = Color(0xFF9090B8),
    DurColor = Color(0xFFB0B0CC),
    commonWhite =  Color(0xFFFFFFFF),
    DividerColo = Color(0xFFEDE8FA),
    ZeroLineCol = Color(0xFFC9BDEE),
    RailBg =Color(0xFFE4DCF7),
    appCommonCo = Color(0xFF5E40B3),
    equBandsBg          = Color(0xFFF7F5FF),
    nobTop = Color(0xFF7C60C8),
    equKnobBot          = Color(0xFF3A2A80),
            equKnobBorder       = Color(0xFF8B6FD0)

)

val DarkCustomColors = CustomColors(
    commonBlackColor = Color(0xFF000000),
    commonWhiteColor = Color(0xFFFFFFFF),
    appCommonColor = Color(0xFF5E40B3),
    placeHolderColor = Color(0xFFA3A3A3),
    SheetBg = Color(0xFFF2F0E9),
    BandsBg = Color(0xFFE8E5DD),
    BandsBorder = Color(0xFFD8D5CD),
    TrackColor = Color(0xFFC8C5BD),
    TrackBorder = Color(0xFFB5B2AA),
    ThumbTop = Color(0xFFFFFFFF),
    ThumbBot = Color(0xFFD0CEC6),
    KnobTop = Color(0xFFFFFFFF),
    KnobBot = Color(0xFFC2C0B8),
    KnobBorder = Color(0xFFB5B2AA),
    AccentRed = Color(0xFFFF4444),
    LabelGray = Color(0xFFAAAAAA),
    TitleColor = Color(0xFF333333),
    PresetActive = Color(0xFF222222),
    PresetInactive = Color(0xFFE8E5DD),
    PresetBorder = Color(0xFFCCC8C0),
    DividerColor = Color(0xFFDAD8D0),
    HandleColor = Color(0xFFCCCAC2),
    ZeroLineColor = Color(0x33FF3C3C),
    PlayingCard = Color(0xBFFFFFFF),
    GlassWhite = Color(0x73FFFFFF),
    PlayingBorder = Color(0x66A478FF),
    GlassBorder = Color(0xBFFFFFFF),
    PlayingTitle = Color(0xFF7040CC),
    SubColor = Color(0xFF9090B8),
    DurColor = Color(0xFFB0B0CC),
    commonWhite =  Color(0xFFFFFFFF),
    DividerColo = Color(0xFFEDE8FA),
    ZeroLineCol = Color(0xFFC9BDEE),
    RailBg = Color(0xFFE4DCF7),
    appCommonCo = Color(0xFF5E40B3),
    equBandsBg          = Color(0xFFF7F5FF),
    nobTop = Color(0xFF7C60C8),
    equKnobBot          = Color(0xFF3A2A80),
    equKnobBorder       = Color(0xFF8B6FD0)
)


val LocalCustomColors = staticCompositionLocalOf { LightCustomColors }